/*
 * "Commons Clause" License Condition v1.0
 *
 * The Software is provided to you by the Licensor under the
 * License, as defined below, subject to the following condition.
 *
 * Without limiting other conditions in the License, the grant
 * of rights under the License will not include, and the
 * License does not grant to you, the right to Sell the Software.
 *
 * For purposes of the foregoing, "Sell" means practicing any
 * or all of the rights granted to you under the License to
 * provide to third parties, for a fee or other consideration
 * (including without limitation fees for hosting or
 * consulting/ support services related to the Software), a
 * product or service whose value derives, entirely or substantially,
 * from the functionality of the Software. Any
 * license notice or attribution required by the License must
 * also include this Commons Clause License Condition notice.
 *
 * License: LGPL 2.1 or later
 * Licensor: metaphacts GmbH
 *
 * Copyright (C) 2015-2021, metaphacts GmbH
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, you can receive a copy
 * of the GNU Lesser General Public License from http://www.gnu.org/
 */
import * as React from 'react';
import { DiagramModel } from '../diagram/model';
import { DiagramView } from '../diagram/view';

import { ElementIri, ElementModel, Property } from '../data/model';
import { Link } from '../diagram/elements';
import { SizeProvider } from '../diagram/geometry';

export type TypeStyleResolver = (types: string[]) => CustomTypeStyle | undefined;
export type ElementStyleResolver = (element: ElementModel) => CustomTypeStyle | undefined;
export type LinkTemplateResolver = (linkType: string) => LinkTemplate | undefined;
export type TemplateResolver = (types: string[]) => ElementTemplate | undefined;

export interface CustomTypeStyle {
    color?: string;
    icon?: string;
}

export type ElementTemplate = React.ComponentClass<TemplateProps>;

export interface TemplateProps {
    /**
     * ID of the element
     */
    elementId: string;

    /**
     *  Raw element model
     */
    data: ElementModel;

    /**
     * IRI of the element
     */
    iri: ElementIri;

    /**
     * A string which is a concatenation of the element's types
     */
    types?: string;

    /**
     * Label of the element
     */
    label: string;

    /**
     * Color generated by Ontodia represented in CSS format
     */
    color: string;

    /**
     * Name of a CSS class which is used to style the icon of the element
     */
    iconUrl?: string;

    /**
     * URL to the element's image
     */
    imgUrl?: string;

    /**
     * `true` if the element is expanded and `false` if collapsed
     */
    isExpanded?: boolean;

    /**
     * Collections of the element's properties
     */
    propsAsList: PropArray;

    /**
     * Map of the element's properties
     */
    props: { [propertyIri: string]: Property | undefined };
}

export type PropArray = Array<{
    id: string;
    name: string;
    property: Property;
}>;

export interface LinkTemplate {
    markerSource?: LinkMarkerStyle | null;
    markerTarget?: Partial<LinkMarkerStyle> | null;
    renderLink?(link: Link, view: DiagramView): LinkStyle;
    setLinkLabel?: ((link: Link, label: string) => void) | null;
}

export interface LinkStyle {
    connection?: {
        fill?: string;
        stroke?: string;
        'stroke-width'?: number;
        'stroke-dasharray'?: string;
    };
    label?: LinkLabel;
    properties?: LinkLabel[];
}

export interface LinkRouter {
    route(model: DiagramModel, sizeProvider: SizeProvider): RoutedLinks;
}

export type RoutedLinks = Map<string, RoutedLink>;

export interface RoutedLink {
    linkId: string;
    vertices: ReadonlyArray<Vertex>;
    labelTextAnchor?: 'start' | 'middle' | 'end';
}

export interface Vertex {
    x: number;
    y: number;
}

export interface LinkMarkerStyle {
    /** @default "M0,0 L0,8 L9,4 z" */
    d: string;
    /** @default 9 */
    width: number;
    /** @default 8 */
    height: number;
    /** @default "black" */
    fill: string;
    /** @default 1 */
    fillOpacity?: number;
    /** @default "none" */
    stroke?: string;
    /** @default 1 */
    strokeWidth?: number;
    /** @default 1 */
    strokeOpacity?: number;
}

export interface LinkLabel {
    position?: number;
    title?: string;
    content?: React.ReactNode | null;
    rectStyle?: React.CSSProperties;
    textStyle?: React.CSSProperties;
}
