/*
 * "Commons Clause" License Condition v1.0
 *
 * The Software is provided to you by the Licensor under the
 * License, as defined below, subject to the following condition.
 *
 * Without limiting other conditions in the License, the grant
 * of rights under the License will not include, and the
 * License does not grant to you, the right to Sell the Software.
 *
 * For purposes of the foregoing, "Sell" means practicing any
 * or all of the rights granted to you under the License to
 * provide to third parties, for a fee or other consideration
 * (including without limitation fees for hosting or
 * consulting/ support services related to the Software), a
 * product or service whose value derives, entirely or substantially,
 * from the functionality of the Software. Any
 * license notice or attribution required by the License must
 * also include this Commons Clause License Condition notice.
 *
 * License: LGPL 2.1 or later
 * Licensor: metaphacts GmbH
 *
 * Copyright (C) 2015-2020, metaphacts GmbH
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, you can receive a copy
 * of the GNU Lesser General Public License from http://www.gnu.org/
 */
import { ComponentClass } from 'react';

/**
 * That is a special require, custom-components module will be generated by
 * webpack custom componentsLoader that uses component.json file to create
 * set of dynamic 'System.import' for web components.
 */
const getBundleLoader = require('platform-components') as
  (tagName: string) => ComponentEntry | null;

interface ComponentEntry {
  loader: () => Promise<ComponentClass<any>>;
  metadata?: ComponentMetadata | null;
}

export interface ComponentMetadata {
  deferAttributes?: { [attrName: string]: boolean };
  deferJsonProperties?: { [attrName: string]: DeferredJsonProperties };
}

export interface DeferredJsonProperties {
  [jsonKey: string]: boolean;
}

const loadingComponents = new Map<string, Promise<ComponentClass<any>>>();
const cachedComponents = new Map<string, ComponentClass<any>>();

/**
 * Asynchronously load JS file for React based web-component.
 */
export function loadComponent(tagName: string): Promise<ComponentClass<any>> {
  if (cachedComponents.has(tagName)) {
    return Promise.resolve(cachedComponents.get(tagName));
  }
  if (loadingComponents.has(tagName)) {
    return loadingComponents.get(tagName);
  }
  const entry = getBundleLoader(tagName);
  if (entry) {
    const task = entry.loader().then((component: any) => {
      const comp = component.default ? component.default : component;
      if (!cachedComponents.has(tagName)) {
        cachedComponents.set(tagName, comp);
        loadingComponents.delete(tagName);
      }
      return comp;
    });
    loadingComponents.set(tagName, task);
    return task;
  } else {
    return Promise.reject(`Cannot find component <${tagName}>`);
  }
}

export function loadComponentSync(tagName: string): ComponentClass<any> {
  if (cachedComponents.has(tagName)) {
    return cachedComponents.get(tagName);
  }

  if (hasComponent(tagName)) {
    throw new Error(`Cannot synchronously load component <${tagName}> as it is not preloaded`);
  } else {
    throw new Error(`Cannot find component <${tagName}>`);
  }
}

export async function loadComponents(tags: ReadonlySet<string>): Promise<void> {
  const componentsToLoad: string[] = [];
  tags.forEach(component => {
    if (!hasCachedComponent(component) && hasComponent(component)) {
      componentsToLoad.push(component);
    }
  });
  if (componentsToLoad.length > 0) {
    await Promise.all(
      componentsToLoad.map(tag => loadComponent(tag))
    );
  }
}

export function hasCachedComponent(tagName: string): boolean {
  return cachedComponents.has(tagName);
}

/**
 * Check if there is React component that corresponds to tagName.
 */
export function hasComponent(tagName: string): boolean {
  const entry = getBundleLoader(tagName);
  return Boolean(entry);
}

export function getComponentMetadata(tagName: string): ComponentMetadata | null | undefined {
  const entry = getBundleLoader(tagName);
  if (!entry) {
    throw new Error(`Cannot find component <${tagName}>`);
  }
  return entry.metadata;
}

export interface ComponentClassMetadata {
  __htmlTag?: string;
}
